/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TherapistPortalRouteImport } from './routes/therapist-portal'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionRouteImport } from './routes/session'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as ParentsHubRouteImport } from './routes/parents-hub'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as GiftRouteImport } from './routes/gift'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TherapistsIndexRouteImport } from './routes/therapists.index'
import { Route as TherapistsIdRouteImport } from './routes/therapists.$id'
import { Route as ProgramsStudentRouteImport } from './routes/programs.student'
import { Route as ProgramsFamilyRouteImport } from './routes/programs.family'
import { Route as PartnersDoctorRouteImport } from './routes/partners.doctor'
import { Route as PartnersCorporateRouteImport } from './routes/partners.corporate'
import { Route as PartnersClinicalRouteImport } from './routes/partners.clinical'
import { Route as BookingIdRouteImport } from './routes/booking.$id'
import { Route as ApiCompanionChatRouteImport } from './routes/api/companion-chat'

const TherapistPortalRoute = TherapistPortalRouteImport.update({
  id: '/therapist-portal',
  path: '/therapist-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsHubRoute = ParentsHubRouteImport.update({
  id: '/parents-hub',
  path: '/parents-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftRoute = GiftRouteImport.update({
  id: '/gift',
  path: '/gift',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapistsIndexRoute = TherapistsIndexRouteImport.update({
  id: '/therapists/',
  path: '/therapists/',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapistsIdRoute = TherapistsIdRouteImport.update({
  id: '/therapists/$id',
  path: '/therapists/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsStudentRoute = ProgramsStudentRouteImport.update({
  id: '/programs/student',
  path: '/programs/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsFamilyRoute = ProgramsFamilyRouteImport.update({
  id: '/programs/family',
  path: '/programs/family',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersDoctorRoute = PartnersDoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => PartnersRoute,
} as any)
const PartnersCorporateRoute = PartnersCorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => PartnersRoute,
} as any)
const PartnersClinicalRoute = PartnersClinicalRouteImport.update({
  id: '/clinical',
  path: '/clinical',
  getParentRoute: () => PartnersRoute,
} as any)
const BookingIdRoute = BookingIdRouteImport.update({
  id: '/booking/$id',
  path: '/booking/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompanionChatRoute = ApiCompanionChatRouteImport.update({
  id: '/api/companion-chat',
  path: '/api/companion-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gift': typeof GiftRoute
  '/journal': typeof JournalRoute
  '/journey': typeof JourneyRoute
  '/parents-hub': typeof ParentsHubRoute
  '/partners': typeof PartnersRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/resources': typeof ResourcesRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/therapist-portal': typeof TherapistPortalRoute
  '/api/companion-chat': typeof ApiCompanionChatRoute
  '/booking/$id': typeof BookingIdRoute
  '/partners/clinical': typeof PartnersClinicalRoute
  '/partners/corporate': typeof PartnersCorporateRoute
  '/partners/doctor': typeof PartnersDoctorRoute
  '/programs/family': typeof ProgramsFamilyRoute
  '/programs/student': typeof ProgramsStudentRoute
  '/therapists/$id': typeof TherapistsIdRoute
  '/therapists/': typeof TherapistsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gift': typeof GiftRoute
  '/journal': typeof JournalRoute
  '/journey': typeof JourneyRoute
  '/parents-hub': typeof ParentsHubRoute
  '/partners': typeof PartnersRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/resources': typeof ResourcesRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/therapist-portal': typeof TherapistPortalRoute
  '/api/companion-chat': typeof ApiCompanionChatRoute
  '/booking/$id': typeof BookingIdRoute
  '/partners/clinical': typeof PartnersClinicalRoute
  '/partners/corporate': typeof PartnersCorporateRoute
  '/partners/doctor': typeof PartnersDoctorRoute
  '/programs/family': typeof ProgramsFamilyRoute
  '/programs/student': typeof ProgramsStudentRoute
  '/therapists/$id': typeof TherapistsIdRoute
  '/therapists': typeof TherapistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gift': typeof GiftRoute
  '/journal': typeof JournalRoute
  '/journey': typeof JourneyRoute
  '/parents-hub': typeof ParentsHubRoute
  '/partners': typeof PartnersRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/resources': typeof ResourcesRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/therapist-portal': typeof TherapistPortalRoute
  '/api/companion-chat': typeof ApiCompanionChatRoute
  '/booking/$id': typeof BookingIdRoute
  '/partners/clinical': typeof PartnersClinicalRoute
  '/partners/corporate': typeof PartnersCorporateRoute
  '/partners/doctor': typeof PartnersDoctorRoute
  '/programs/family': typeof ProgramsFamilyRoute
  '/programs/student': typeof ProgramsStudentRoute
  '/therapists/$id': typeof TherapistsIdRoute
  '/therapists/': typeof TherapistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/gift'
    | '/journal'
    | '/journey'
    | '/parents-hub'
    | '/partners'
    | '/privacy'
    | '/quiz'
    | '/resources'
    | '/session'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/therapist-portal'
    | '/api/companion-chat'
    | '/booking/$id'
    | '/partners/clinical'
    | '/partners/corporate'
    | '/partners/doctor'
    | '/programs/family'
    | '/programs/student'
    | '/therapists/$id'
    | '/therapists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/gift'
    | '/journal'
    | '/journey'
    | '/parents-hub'
    | '/partners'
    | '/privacy'
    | '/quiz'
    | '/resources'
    | '/session'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/therapist-portal'
    | '/api/companion-chat'
    | '/booking/$id'
    | '/partners/clinical'
    | '/partners/corporate'
    | '/partners/doctor'
    | '/programs/family'
    | '/programs/student'
    | '/therapists/$id'
    | '/therapists'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/gift'
    | '/journal'
    | '/journey'
    | '/parents-hub'
    | '/partners'
    | '/privacy'
    | '/quiz'
    | '/resources'
    | '/session'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/therapist-portal'
    | '/api/companion-chat'
    | '/booking/$id'
    | '/partners/clinical'
    | '/partners/corporate'
    | '/partners/doctor'
    | '/programs/family'
    | '/programs/student'
    | '/therapists/$id'
    | '/therapists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GiftRoute: typeof GiftRoute
  JournalRoute: typeof JournalRoute
  JourneyRoute: typeof JourneyRoute
  ParentsHubRoute: typeof ParentsHubRoute
  PartnersRoute: typeof PartnersRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  QuizRoute: typeof QuizRoute
  ResourcesRoute: typeof ResourcesRoute
  SessionRoute: typeof SessionRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  TherapistPortalRoute: typeof TherapistPortalRoute
  ApiCompanionChatRoute: typeof ApiCompanionChatRoute
  BookingIdRoute: typeof BookingIdRoute
  ProgramsFamilyRoute: typeof ProgramsFamilyRoute
  ProgramsStudentRoute: typeof ProgramsStudentRoute
  TherapistsIdRoute: typeof TherapistsIdRoute
  TherapistsIndexRoute: typeof TherapistsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/therapist-portal': {
      id: '/therapist-portal'
      path: '/therapist-portal'
      fullPath: '/therapist-portal'
      preLoaderRoute: typeof TherapistPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents-hub': {
      id: '/parents-hub'
      path: '/parents-hub'
      fullPath: '/parents-hub'
      preLoaderRoute: typeof ParentsHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift': {
      id: '/gift'
      path: '/gift'
      fullPath: '/gift'
      preLoaderRoute: typeof GiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapists/': {
      id: '/therapists/'
      path: '/therapists'
      fullPath: '/therapists/'
      preLoaderRoute: typeof TherapistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapists/$id': {
      id: '/therapists/$id'
      path: '/therapists/$id'
      fullPath: '/therapists/$id'
      preLoaderRoute: typeof TherapistsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/student': {
      id: '/programs/student'
      path: '/programs/student'
      fullPath: '/programs/student'
      preLoaderRoute: typeof ProgramsStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/family': {
      id: '/programs/family'
      path: '/programs/family'
      fullPath: '/programs/family'
      preLoaderRoute: typeof ProgramsFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/doctor': {
      id: '/partners/doctor'
      path: '/doctor'
      fullPath: '/partners/doctor'
      preLoaderRoute: typeof PartnersDoctorRouteImport
      parentRoute: typeof PartnersRoute
    }
    '/partners/corporate': {
      id: '/partners/corporate'
      path: '/corporate'
      fullPath: '/partners/corporate'
      preLoaderRoute: typeof PartnersCorporateRouteImport
      parentRoute: typeof PartnersRoute
    }
    '/partners/clinical': {
      id: '/partners/clinical'
      path: '/clinical'
      fullPath: '/partners/clinical'
      preLoaderRoute: typeof PartnersClinicalRouteImport
      parentRoute: typeof PartnersRoute
    }
    '/booking/$id': {
      id: '/booking/$id'
      path: '/booking/$id'
      fullPath: '/booking/$id'
      preLoaderRoute: typeof BookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/companion-chat': {
      id: '/api/companion-chat'
      path: '/api/companion-chat'
      fullPath: '/api/companion-chat'
      preLoaderRoute: typeof ApiCompanionChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PartnersRouteChildren {
  PartnersClinicalRoute: typeof PartnersClinicalRoute
  PartnersCorporateRoute: typeof PartnersCorporateRoute
  PartnersDoctorRoute: typeof PartnersDoctorRoute
}

const PartnersRouteChildren: PartnersRouteChildren = {
  PartnersClinicalRoute: PartnersClinicalRoute,
  PartnersCorporateRoute: PartnersCorporateRoute,
  PartnersDoctorRoute: PartnersDoctorRoute,
}

const PartnersRouteWithChildren = PartnersRoute._addFileChildren(
  PartnersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GiftRoute: GiftRoute,
  JournalRoute: JournalRoute,
  JourneyRoute: JourneyRoute,
  ParentsHubRoute: ParentsHubRoute,
  PartnersRoute: PartnersRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  QuizRoute: QuizRoute,
  ResourcesRoute: ResourcesRoute,
  SessionRoute: SessionRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  TherapistPortalRoute: TherapistPortalRoute,
  ApiCompanionChatRoute: ApiCompanionChatRoute,
  BookingIdRoute: BookingIdRoute,
  ProgramsFamilyRoute: ProgramsFamilyRoute,
  ProgramsStudentRoute: ProgramsStudentRoute,
  TherapistsIdRoute: TherapistsIdRoute,
  TherapistsIndexRoute: TherapistsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
