/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TherapistPortalRouteImport } from './routes/therapist-portal'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionRouteImport } from './routes/session'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as GiftRouteImport } from './routes/gift'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TherapistsIndexRouteImport } from './routes/therapists.index'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as TherapistsIdRouteImport } from './routes/therapists.$id'
import { Route as PartnersCorporateRouteImport } from './routes/partners.corporate'
import { Route as PartnersClinicalRouteImport } from './routes/partners.clinical'
import { Route as LibrarySlugRouteImport } from './routes/library.$slug'
import { Route as BookingIdRouteImport } from './routes/booking.$id'
import { Route as ApiCompanionChatRouteImport } from './routes/api/companion-chat'

const TherapistPortalRoute = TherapistPortalRouteImport.update({
  id: '/therapist-portal',
  path: '/therapist-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftRoute = GiftRouteImport.update({
  id: '/gift',
  path: '/gift',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapistsIndexRoute = TherapistsIndexRouteImport.update({
  id: '/therapists/',
  path: '/therapists/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapistsIdRoute = TherapistsIdRouteImport.update({
  id: '/therapists/$id',
  path: '/therapists/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersCorporateRoute = PartnersCorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => PartnersRoute,
} as any)
const PartnersClinicalRoute = PartnersClinicalRouteImport.update({
  id: '/clinical',
  path: '/clinical',
  getParentRoute: () => PartnersRoute,
} as any)
const LibrarySlugRoute = LibrarySlugRouteImport.update({
  id: '/library/$slug',
  path: '/library/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingIdRoute = BookingIdRouteImport.update({
  id: '/booking/$id',
  path: '/booking/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompanionChatRoute = ApiCompanionChatRouteImport.update({
  id: '/api/companion-chat',
  path: '/api/companion-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/gift': typeof GiftRoute
  '/journal': typeof JournalRoute
  '/journey': typeof JourneyRoute
  '/partners': typeof PartnersRouteWithChildren
  '/quiz': typeof QuizRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/therapist-portal': typeof TherapistPortalRoute
  '/api/companion-chat': typeof ApiCompanionChatRoute
  '/booking/$id': typeof BookingIdRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/partners/clinical': typeof PartnersClinicalRoute
  '/partners/corporate': typeof PartnersCorporateRoute
  '/therapists/$id': typeof TherapistsIdRoute
  '/library/': typeof LibraryIndexRoute
  '/therapists/': typeof TherapistsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/gift': typeof GiftRoute
  '/journal': typeof JournalRoute
  '/journey': typeof JourneyRoute
  '/partners': typeof PartnersRouteWithChildren
  '/quiz': typeof QuizRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/therapist-portal': typeof TherapistPortalRoute
  '/api/companion-chat': typeof ApiCompanionChatRoute
  '/booking/$id': typeof BookingIdRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/partners/clinical': typeof PartnersClinicalRoute
  '/partners/corporate': typeof PartnersCorporateRoute
  '/therapists/$id': typeof TherapistsIdRoute
  '/library': typeof LibraryIndexRoute
  '/therapists': typeof TherapistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/gift': typeof GiftRoute
  '/journal': typeof JournalRoute
  '/journey': typeof JourneyRoute
  '/partners': typeof PartnersRouteWithChildren
  '/quiz': typeof QuizRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/therapist-portal': typeof TherapistPortalRoute
  '/api/companion-chat': typeof ApiCompanionChatRoute
  '/booking/$id': typeof BookingIdRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/partners/clinical': typeof PartnersClinicalRoute
  '/partners/corporate': typeof PartnersCorporateRoute
  '/therapists/$id': typeof TherapistsIdRoute
  '/library/': typeof LibraryIndexRoute
  '/therapists/': typeof TherapistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/gift'
    | '/journal'
    | '/journey'
    | '/partners'
    | '/quiz'
    | '/session'
    | '/settings'
    | '/therapist-portal'
    | '/api/companion-chat'
    | '/booking/$id'
    | '/library/$slug'
    | '/partners/clinical'
    | '/partners/corporate'
    | '/therapists/$id'
    | '/library/'
    | '/therapists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/gift'
    | '/journal'
    | '/journey'
    | '/partners'
    | '/quiz'
    | '/session'
    | '/settings'
    | '/therapist-portal'
    | '/api/companion-chat'
    | '/booking/$id'
    | '/library/$slug'
    | '/partners/clinical'
    | '/partners/corporate'
    | '/therapists/$id'
    | '/library'
    | '/therapists'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/gift'
    | '/journal'
    | '/journey'
    | '/partners'
    | '/quiz'
    | '/session'
    | '/settings'
    | '/therapist-portal'
    | '/api/companion-chat'
    | '/booking/$id'
    | '/library/$slug'
    | '/partners/clinical'
    | '/partners/corporate'
    | '/therapists/$id'
    | '/library/'
    | '/therapists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  GiftRoute: typeof GiftRoute
  JournalRoute: typeof JournalRoute
  JourneyRoute: typeof JourneyRoute
  PartnersRoute: typeof PartnersRouteWithChildren
  QuizRoute: typeof QuizRoute
  SessionRoute: typeof SessionRoute
  SettingsRoute: typeof SettingsRoute
  TherapistPortalRoute: typeof TherapistPortalRoute
  ApiCompanionChatRoute: typeof ApiCompanionChatRoute
  BookingIdRoute: typeof BookingIdRoute
  LibrarySlugRoute: typeof LibrarySlugRoute
  TherapistsIdRoute: typeof TherapistsIdRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  TherapistsIndexRoute: typeof TherapistsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/therapist-portal': {
      id: '/therapist-portal'
      path: '/therapist-portal'
      fullPath: '/therapist-portal'
      preLoaderRoute: typeof TherapistPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift': {
      id: '/gift'
      path: '/gift'
      fullPath: '/gift'
      preLoaderRoute: typeof GiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapists/': {
      id: '/therapists/'
      path: '/therapists'
      fullPath: '/therapists/'
      preLoaderRoute: typeof TherapistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapists/$id': {
      id: '/therapists/$id'
      path: '/therapists/$id'
      fullPath: '/therapists/$id'
      preLoaderRoute: typeof TherapistsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/corporate': {
      id: '/partners/corporate'
      path: '/corporate'
      fullPath: '/partners/corporate'
      preLoaderRoute: typeof PartnersCorporateRouteImport
      parentRoute: typeof PartnersRoute
    }
    '/partners/clinical': {
      id: '/partners/clinical'
      path: '/clinical'
      fullPath: '/partners/clinical'
      preLoaderRoute: typeof PartnersClinicalRouteImport
      parentRoute: typeof PartnersRoute
    }
    '/library/$slug': {
      id: '/library/$slug'
      path: '/library/$slug'
      fullPath: '/library/$slug'
      preLoaderRoute: typeof LibrarySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$id': {
      id: '/booking/$id'
      path: '/booking/$id'
      fullPath: '/booking/$id'
      preLoaderRoute: typeof BookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/companion-chat': {
      id: '/api/companion-chat'
      path: '/api/companion-chat'
      fullPath: '/api/companion-chat'
      preLoaderRoute: typeof ApiCompanionChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PartnersRouteChildren {
  PartnersClinicalRoute: typeof PartnersClinicalRoute
  PartnersCorporateRoute: typeof PartnersCorporateRoute
}

const PartnersRouteChildren: PartnersRouteChildren = {
  PartnersClinicalRoute: PartnersClinicalRoute,
  PartnersCorporateRoute: PartnersCorporateRoute,
}

const PartnersRouteWithChildren = PartnersRoute._addFileChildren(
  PartnersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  GiftRoute: GiftRoute,
  JournalRoute: JournalRoute,
  JourneyRoute: JourneyRoute,
  PartnersRoute: PartnersRouteWithChildren,
  QuizRoute: QuizRoute,
  SessionRoute: SessionRoute,
  SettingsRoute: SettingsRoute,
  TherapistPortalRoute: TherapistPortalRoute,
  ApiCompanionChatRoute: ApiCompanionChatRoute,
  BookingIdRoute: BookingIdRoute,
  LibrarySlugRoute: LibrarySlugRoute,
  TherapistsIdRoute: TherapistsIdRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  TherapistsIndexRoute: TherapistsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
